site_name: Clash Docs
repo_name: clash-verge-rev
repo_url: https://github.com/clash-verge-rev/clash-verge-rev
copyright: Copyright &copy 2024 clash
edit_uri: https://github.com/tangwenlongNO1/clash-verge-rev.github.io/tree/main/docs

# dev服务器监听地址
dev_addr: 127.0.0.1:7788
# 禁用路由导航方式
use_directory_urls: false

# 导航设置
nav:
  - 简介: index.md
  - 安装: install.md
  - 使用教程:
      - 常见名词: guide/term.md
      - 导出日志: guide/log.md
      - 订阅导入: guide/profile.md
      - Merge配置: guide/merge.md
      - Script配置: guide/script.md
      - 设置代理绕过: guide/bypass.md
      - 设置代理组图标: guide/group_icon/group_icon.md
      - 自定义托盘图标: guide/tray_icon.md
      - 自定义主题/样式: guide/css_injection.md
      - URL Schemes: guide/url_schemes.md
  - 常见问题:
      - Windows: faq/windows.md
      - MacOS: faq/macos.md
      - Linux: faq/linux.md
      - 其他问题: faq/other.md
  - 友情链接: friendship.md
  - 配置:
    - config/index.md
    - 语法: config/syntax.md
    - 全局配置: config/general.md
    - DNS:
      - DNS配置: config/dns/index.md
      - DNS类型: config/dns/type.md
      - hosts: config/dns/hosts.md
      - 解析流程: config/dns/diagram.md
    - 域名嗅探: config/sniff/index.md
    - 入站:
      - 代理端口: config/inbound/port.md
      - Tun: config/inbound/tun.md
      - listeners:
        - 通用字段: config/inbound/listeners/index.md
        - http: config/inbound/listeners/http.md
        - socks: config/inbound/listeners/socks.md
        - mixed: config/inbound/listeners/mixed.md
        - redirect: config/inbound/listeners/redirect.md
        - tproxy: config/inbound/listeners/tproxy.md
        - tun: config/inbound/listeners/tun.md
        - ShadowSocks: config/inbound/listeners/ss.md
        - VMess: config/inbound/listeners/vmess.md
        - TUIC v4: config/inbound/listeners/tuic-v4.md
        - TUIC v5: config/inbound/listeners/tuic-v5.md
        - Hysteria2: config/inbound/listeners/hysteria2.md
        - tunnel: config/inbound/listeners/tunnel.md
    - 出站代理:
      - 通用字段: config/proxies/index.md
      - TLS配置: config/proxies/tls.md
      - 传输层配置: config/proxies/transport.md
      - dialer-proxy: config/proxies/dialer-proxy.md
      - sing-mux: config/proxies/sing-mux.md
      - DIRECT: config/proxies/direct.md
      - DNS: config/proxies/dns.md
      - HTTP: config/proxies/http.md
      - SOCKS: config/proxies/socks.md
      - Shadowsocks: config/proxies/ss.md
      - ShadowsocksR: config/proxies/ssr.md
      - VMess: config/proxies/vmess.md
      - VLESS: config/proxies/vless.md
      - Trojan: config/proxies/trojan.md
      - Hysteria: config/proxies/hysteria.md
      - Hysteria2: config/proxies/hysteria2.md
      - TUIC: config/proxies/tuic.md
      - WireGuard: config/proxies/wg.md
      - SSH: config/proxies/ssh.md
    - 代理集合:
      - 代理集合配置: config/proxy-providers/index.md
      - 代理集合内容: config/proxy-providers/content.md
    - 策略组:
      - 策略组配置: config/proxy-groups/index.md
      - 手动选择: config/proxy-groups/select.md
      - 自动选择: config/proxy-groups/url-test.md
      - 自动回退: config/proxy-groups/fallback.md
      - 负载均衡: config/proxy-groups/load-balance.md
      - 链式代理: config/proxy-groups/relay.md
      - 内置策略: config/proxy-groups/built-in.md
    - 路由规则: config/rules/index.md
      # - 域名规则: config/rules/domain.md
      # - IP规则: config/rules/ip.md
      # - 端口规则: config/rules/port.md
      # - 进程规则: config/rules/process.md
      # - 逻辑规则: config/rules/logic.md
      # - GEO规则: config/rules/geox.md
      # - 入站规则: config/rules/in.md
      # - 网络类型规则: config/rules/network.md
      # - 引用规则集合: config/rules/rule-set.md
      # - 引用子规则: config/rules/sub-rule.md
      # - 最终匹配: config/rules/match.md
    - 规则集合: 
      - 规则集合: config/rule-providers/index.md
      - 规则集合内容: config/rule-providers/content.md
    - 子规则: config/sub-rule.md
    - 流量隧道: config/tunnels.md
    - NTP: config/ntp/index.md
    - 实验性配置: config/experimental.md
  - APIs: api/index.md

# 主题设置
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - search.highlight
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - content.action.edit
    - content.code.copy
  # 亮色/深色模式
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

# markdown特性设置
markdown_extensions:
  - admonition # 提醒框、警告框等
  - md_in_html # 支持嵌入HTML代码
  - pymdownx.details # 支持<details>折叠标签
  - pymdownx.tilde # 支持~表示删除的文本
  - pymdownx.magiclink # 自动将URL转换为可点击的链接
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3
      anchorlink: true
  # mermaid渲染
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\u200b\-]'

extra:
  generator: false # 去除页脚广告
  social: # 页脚链接
    - icon: fontawesome/brands/github
      link: https://github.com/clash-verge-rev/clash-verge-rev
    - icon: material/file-document
      link: https://github.com/tangwenlongNO1/clash-verge-rev.github.io
